spring.application.name=TS

spring.datasource.url=jdbc:postgresql://dpg-d7t3qm0k1i2s73aakr10-a:5432/toy_store_hxxt
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}

logging.level.root=INFO
logging.level.com.example.ts=DEBUG
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache=ERROR