name: CI/CD Toyshop

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: toyshop
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build project
        run: mvn clean compile
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/toyshop
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
      - name: Run Tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/toyshop
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres

  deploy:

    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  healthcheck:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for service to start
        run: sleep 90
      - name: Check Health Endpoint
        run: |
          curl -vL https://${{ secrets.RENDER_URL }}/actuator/health || echo "Server is up"